Traceback (most recent call last):
  File "/data/npl/Speech2Text/rna/conv-rnnt/train.py", line 200, in <module>
    main()
  File "/data/npl/Speech2Text/rna/conv-rnnt/train.py", line 145, in main
    model.to(device)
  File "/data/npl/Speech2Text/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
  File "/data/npl/Speech2Text/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/data/npl/Speech2Text/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/data/npl/Speech2Text/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/data/npl/Speech2Text/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 942, in _apply
    param_applied = fn(param)
  File "/data/npl/Speech2Text/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1341, in convert
    return t.to(
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

